

class FindingNotFoundError(Exception):
    pass


class UserNotFoundError(Exception):
    pass
